sonar.projectKey=FleetOps-Frontend
sonar.projectName=FleetOps Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/coverage/**,**/dist/**,**/build/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S7785
sonar.issue.ignore.multicriteria.e1.resourceKey=src/main.jsx
